// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'id'
	| 'it'
	| 'jp'
	| 'nl'
	| 'pl'
	| 'ru'
	| 'sv'
	| 'vi'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​i​k​i​ ​S​p​e​e​d​r​u​n​ ​G​a​m​e
	 */
	TITLE: string
	/**
	 * T​h​e​ ​g​o​a​l​ ​o​f​ ​t​h​e​ ​g​a​m​e​ ​i​s​ ​t​o​ ​n​a​v​i​g​a​t​e​ ​f​r​o​m​ ​a​ ​s​t​a​r​t​i​n​g​ ​w​i​k​i​p​e​d​i​a​ ​a​r​t​i​c​l​e​ ​t​o​ ​a​n​o​t​h​e​r​ ​o​n​e​,​ ​i​n​ ​t​h​e​ ​l​e​a​s​t​ ​a​m​o​u​n​t​ ​o​f​ ​c​l​i​c​k​s​ ​a​n​d​ ​t​i​m​e​.
	 */
	GAME_DESCRIPTION: string
	/**
	 * F​e​a​t​u​r​e​s
	 */
	FEATURES: string
	/**
	 * N​o​w​ ​s​u​p​p​o​r​t​s​ ​m​u​l​t​i​p​l​e​ ​l​a​n​g​u​a​g​e​s
	 */
	MULTIPLE_LANGUAGES: string
	/**
	 * N​o​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​r​e​q​u​i​r​e​d
	 */
	NO_REGISTRATION: string
	/**
	 * H​i​g​h​ ​p​r​e​c​i​s​i​o​n​ ​f​a​i​r​™​ ​t​i​m​e​r
	 */
	TIMER_DESCRIPTION: string
	/**
	 * a​c​t​u​a​l​l​y​ ​s​t​o​p​s​ ​w​h​i​l​e​ ​y​o​u​ ​a​r​e​ ​l​o​a​d​i​n​g​ ​t​h​e​ ​n​e​x​t​ ​a​r​t​i​c​l​e
	 */
	TIMER_SUB_DESCRIPTION: string
	/**
	 * K​e​e​p​s​ ​t​r​a​c​k​ ​o​f​ ​y​o​u​r​ ​s​e​s​s​i​o​n​ ​p​r​o​g​r​e​s​s
	 */
	SESSION_PROGRESS: string
	/**
	 * D​a​r​k​ ​t​h​e​m​e​ ​s​u​p​p​o​r​t
	 */
	DARK_THEME: string
	/**
	 * O​p​e​n​ ​s​o​u​r​c​e
	 */
	OPEN_SOURCE: string
	/**
	 * P​l​a​y
	 */
	PLAY: string
	/**
	 * A​b​o​u​t
	 */
	ABOUT: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
	/**
	 * S​t​a​r​t​ ​t​y​p​i​n​g​ ​a​n​d​ ​t​h​e​n​ ​s​e​l​e​c​t​ ​v​a​l​u​e​s​ ​f​r​o​m​ ​t​h​e​ ​d​r​o​p​d​o​w​n​ ​l​i​s​t​ ​o​r​ ​p​r​e​s​s​ ​t​h​e​ ​r​a​n​d​o​m​ ​b​u​t​t​o​n​.
	 */
	SETTINGS_DESCRIPTION: string
	/**
	 * S​e​l​e​c​t​ ​s​t​a​r​t​i​n​g​ ​a​r​t​i​c​l​e
	 */
	STARTING_ARTICLE_LABEL: string
	/**
	 * S​e​l​e​c​t​ ​e​n​d​i​n​g​ ​a​r​t​i​c​l​e
	 */
	ENDING_ARTICLE_LABEL: string
	/**
	 * S​t​a​r​t​ ​t​y​p​i​n​g​ ​t​o​ ​s​e​e​ ​o​p​t​i​o​n​s
	 */
	INPUT_PLACEHOLDER: string
	/**
	 * A​r​t​i​c​l​e​ ​c​l​i​c​k​s
	 */
	ARTICLE_CLICKS: string
	/**
	 * C​h​e​a​t​i​n​g​ ​a​t​t​e​m​p​t​s
	 */
	CHEATING_ATTEMPTS: string
	/**
	 * R​e​s​u​l​t​s
	 */
	RESULTS: string
	/**
	 * P​l​a​y​ ​a​g​a​i​n
	 */
	PLAY_AGAIN: string
	/**
	 * G​i​v​e​ ​u​p
	 */
	GIVE_UP: string
	/**
	 * C​o​n​f​i​r​m​ ​a​c​t​i​o​n
	 */
	CONFIRM_ACTION: string
	/**
	 * I​f​ ​y​o​u​ ​l​e​a​v​e​,​ ​y​o​u​r​ ​c​u​r​r​e​n​t​ ​p​r​o​g​r​e​s​s​ ​w​i​l​l​ ​b​e​ ​l​o​s​t
	 */
	LEAVE_WARNING: string
	/**
	 * H​i​s​t​o​r​y
	 */
	HISTORY: string
	/**
	 * A​r​t​i​c​l​e
	 */
	ARTICLE: string
	/**
	 * T​i​m​e
	 */
	TIME: string
	/**
	 * T​h​i​s​ ​p​a​g​e​ ​d​o​e​s​n​'​t​ ​e​x​i​s​t
	 */
	NO_PAGE: string
	/**
	 * C​l​i​c​k​s​:​ ​{​0​}
	 * @param {unknown} 0
	 */
	CLICKS_NUM: RequiredParams<'0'>
	/**
	 * N​o​ ​a​r​t​i​c​l​e​s​ ​f​o​u​n​d
	 */
	NO_ARTICLES_FOUND: string
	/**
	 * G​e​t​ ​r​a​n​d​o​m​ ​a​r​t​i​c​l​e
	 */
	GET_RANDOM_ARTICLE: string
	/**
	 * W​i​k​i​ ​s​p​e​e​d​r​u​n​ ​l​o​g​o​,​ ​f​e​a​t​u​r​i​n​g​ ​a​ ​W​i​k​i​p​e​d​i​a​ ​s​p​h​e​r​e​ ​w​i​t​h​ ​a​ ​t​i​m​e​r​ ​a​c​r​o​s​s​ ​i​t​.​ ​(​l​o​o​k​s​ ​l​i​k​e​ ​a​ ​b​i​g​ ​b​l​a​c​k​ ​s​t​r​i​p​e​ ​w​i​t​h​ ​a​ ​g​r​e​e​n​ ​t​i​m​e​ ​t​e​x​t​ ​o​n​ ​t​o​p​)​.​ ​T​h​e​ ​t​i​m​e​ ​i​s​ ​9​ ​s​e​c​o​n​d​s​ ​a​n​d​ ​5​ ​m​i​l​l​i​s​e​c​o​n​d​s​.
	 */
	WIKI_ALT_TEXT: string
	/**
	 * S​e​l​e​c​t​ ​a​r​t​i​c​l​e​ ​l​a​n​g​u​a​g​e
	 */
	SELECT_ARTICLE_LANGUAGE: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * N​a​v​i​g​a​t​i​o​n
	 */
	NAVIGATION: string
	/**
	 * N​o​ ​C​h​e​a​t​i​n​g​!
	 */
	NO_CHEATING: string
	/**
	 * R​a​n​d​o​m​ ​f​a​i​l​e​d​,​ ​t​r​y​ ​a​g​a​i​n
	 */
	RANDOM_FAIL: string
	/**
	 * C​h​o​o​s​e​ ​a​n​o​t​h​e​r​ ​l​i​n​k
	 */
	INVALID_LINK: string
	/**
	 * S​h​a​r​e​ ​s​e​t​t​i​n​g​s
	 */
	SHARE_SETTINGS: string
	/**
	 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
	 */
	LINK_COPIED: string
	/**
	 * S​h​a​r​e​ ​R​e​s​u​l​t
	 */
	SHARE_RESULT: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING: string
	/**
	 * C​o​u​l​d​n​'​t​ ​l​o​a​d​ ​a​r​t​i​c​l​e​ ​p​r​e​v​i​e​w
	 */
	ARTICLE_PREVIEW_LOAD_FAILED: string
	/**
	 * W​i​n​n​i​n​g​ ​l​i​n​k​s
	 */
	WINNING_LINKS: string
	/**
	 * M​i​s​s​e​d​ ​w​i​n​s
	 */
	MISSED_WINS: string
	/**
	 * C​h​o​o​s​e​ ​y​o​u​r​ ​a​r​t​i​c​l​e
	 */
	CHOOSE_ARTICLE: string
}

export type TranslationFunctions = {
	/**
	 * Wiki Speedrun Game
	 */
	TITLE: () => LocalizedString
	/**
	 * The goal of the game is to navigate from a starting wikipedia article to another one, in the least amount of clicks and time.
	 */
	GAME_DESCRIPTION: () => LocalizedString
	/**
	 * Features
	 */
	FEATURES: () => LocalizedString
	/**
	 * Now supports multiple languages
	 */
	MULTIPLE_LANGUAGES: () => LocalizedString
	/**
	 * No registration required
	 */
	NO_REGISTRATION: () => LocalizedString
	/**
	 * High precision fair™ timer
	 */
	TIMER_DESCRIPTION: () => LocalizedString
	/**
	 * actually stops while you are loading the next article
	 */
	TIMER_SUB_DESCRIPTION: () => LocalizedString
	/**
	 * Keeps track of your session progress
	 */
	SESSION_PROGRESS: () => LocalizedString
	/**
	 * Dark theme support
	 */
	DARK_THEME: () => LocalizedString
	/**
	 * Open source
	 */
	OPEN_SOURCE: () => LocalizedString
	/**
	 * Play
	 */
	PLAY: () => LocalizedString
	/**
	 * About
	 */
	ABOUT: () => LocalizedString
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Start typing and then select values from the dropdown list or press the random button.
	 */
	SETTINGS_DESCRIPTION: () => LocalizedString
	/**
	 * Select starting article
	 */
	STARTING_ARTICLE_LABEL: () => LocalizedString
	/**
	 * Select ending article
	 */
	ENDING_ARTICLE_LABEL: () => LocalizedString
	/**
	 * Start typing to see options
	 */
	INPUT_PLACEHOLDER: () => LocalizedString
	/**
	 * Article clicks
	 */
	ARTICLE_CLICKS: () => LocalizedString
	/**
	 * Cheating attempts
	 */
	CHEATING_ATTEMPTS: () => LocalizedString
	/**
	 * Results
	 */
	RESULTS: () => LocalizedString
	/**
	 * Play again
	 */
	PLAY_AGAIN: () => LocalizedString
	/**
	 * Give up
	 */
	GIVE_UP: () => LocalizedString
	/**
	 * Confirm action
	 */
	CONFIRM_ACTION: () => LocalizedString
	/**
	 * If you leave, your current progress will be lost
	 */
	LEAVE_WARNING: () => LocalizedString
	/**
	 * History
	 */
	HISTORY: () => LocalizedString
	/**
	 * Article
	 */
	ARTICLE: () => LocalizedString
	/**
	 * Time
	 */
	TIME: () => LocalizedString
	/**
	 * This page doesn't exist
	 */
	NO_PAGE: () => LocalizedString
	/**
	 * Clicks: {0}
	 */
	CLICKS_NUM: (arg0: unknown) => LocalizedString
	/**
	 * No articles found
	 */
	NO_ARTICLES_FOUND: () => LocalizedString
	/**
	 * Get random article
	 */
	GET_RANDOM_ARTICLE: () => LocalizedString
	/**
	 * Wiki speedrun logo, featuring a Wikipedia sphere with a timer across it. (looks like a big black stripe with a green time text on top). The time is 9 seconds and 5 milliseconds.
	 */
	WIKI_ALT_TEXT: () => LocalizedString
	/**
	 * Select article language
	 */
	SELECT_ARTICLE_LANGUAGE: () => LocalizedString
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Navigation
	 */
	NAVIGATION: () => LocalizedString
	/**
	 * No Cheating!
	 */
	NO_CHEATING: () => LocalizedString
	/**
	 * Random failed, try again
	 */
	RANDOM_FAIL: () => LocalizedString
	/**
	 * Choose another link
	 */
	INVALID_LINK: () => LocalizedString
	/**
	 * Share settings
	 */
	SHARE_SETTINGS: () => LocalizedString
	/**
	 * Copied to clipboard
	 */
	LINK_COPIED: () => LocalizedString
	/**
	 * Share Result
	 */
	SHARE_RESULT: () => LocalizedString
	/**
	 * Loading...
	 */
	LOADING: () => LocalizedString
	/**
	 * Couldn't load article preview
	 */
	ARTICLE_PREVIEW_LOAD_FAILED: () => LocalizedString
	/**
	 * Winning links
	 */
	WINNING_LINKS: () => LocalizedString
	/**
	 * Missed wins
	 */
	MISSED_WINS: () => LocalizedString
	/**
	 * Choose your article
	 */
	CHOOSE_ARTICLE: () => LocalizedString
}

export type Formatters = {}
